version: "3"

services:
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/var/www/html
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    tty: true

  node:
    image: node:lts
    volumes:
      - ./resources/assets:/var/www/ui
    working_dir: /var/www/ui
    tty: true

  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./docker/mysql/databases:/var/lib/mysql
      - ./var/docker/log/mysql:/var/log/mysql

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www/html
      - ./var/docker/log/nginx:/var/log/nginx
    ports:
      - "8080:80"